//! Dev-only generator for the vendored map data tables.
//!
//! `cargo xtask gen-map-data` fetches the pinned upstream sources and rewrites
//! `src/tui/map/coastline.rs` and `src/tui/map/zone_coords.rs`. The tables are
//! committed so the main build stays offline; this tool exists so they are
//! reproducible instead of hand-maintained, and CI regenerates then diffs to
//! catch drift.
//!
//! Fetching shells out to the system `curl` to keep the dev dependency tree
//! tiny (no bundled TLS stack), which also keeps `cargo deny` green.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use serde_json::Value;

/// Pinned upstream revision of `nvkelso/natural-earth-vector`.
const NE_REF: &str = "v5.1.2";
/// Pinned upstream revision of `eggert/tz`.
const TZ_REF: &str = "2026a";

fn main() -> Result<()> {
    match std::env::args().nth(1).as_deref() {
        Some("gen-map-data") => gen_map_data(),
        Some(other) => bail!("unknown command {other:?}; try `cargo xtask gen-map-data`"),
        None => bail!("usage: cargo xtask gen-map-data"),
    }
}

/// Repository root; the xtask crate lives at `<root>/xtask`.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate has a parent directory")
        .to_path_buf()
}

fn gen_map_data() -> Result<()> {
    let root = repo_root();

    let targets = [
        ("src/tui/map/coastline.rs", gen_coastline()?),
        ("src/tui/map/zone_coords.rs", gen_zone_coords()?),
    ];
    for (rel, contents) in targets {
        let path = root.join(rel);
        std::fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

/// Fetch a URL as text via the system `curl`.
fn fetch(url: &str) -> Result<String> {
    let out = Command::new("curl")
        .args(["-sSfL", "--retry", "3", url])
        .output()
        .with_context(|| format!("running curl for {url}"))?;
    if !out.status.success() {
        bail!(
            "curl failed for {url}: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    String::from_utf8(out.stdout).context("response was not UTF-8")
}

/// Round to two decimals and print the shortest literal that keeps one decimal
/// digit (`141` -> `141.0`, `-2.60` -> `-2.6`), normalising negative zero.
fn fmt_coord(v: f64) -> String {
    let s = format!("{v:.2}");
    let trimmed = s.trim_end_matches('0');
    let out = if trimmed.ends_with('.') {
        format!("{trimmed}0")
    } else {
        trimmed.to_string()
    };
    if out == "-0.0" {
        "0.0".to_string()
    } else {
        out
    }
}

fn gen_coastline() -> Result<String> {
    let raw = fetch(&format!(
        "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/{NE_REF}/geojson/ne_110m_coastline.geojson"
    ))?;
    let json: Value = serde_json::from_str(&raw).context("parsing coastline GeoJSON")?;
    let features = json["features"]
        .as_array()
        .context("GeoJSON has no features array")?;

    let mut body = String::new();
    for feature in features {
        let geom = &feature["geometry"];
        let kind = geom["type"].as_str().context("geometry has no type")?;
        let coords = &geom["coordinates"];
        match kind {
            "LineString" => writeln!(body, "    {},", emit_line(coords)?)?,
            "MultiLineString" => {
                for line in coords.as_array().context("MultiLineString coordinates")? {
                    writeln!(body, "    {},", emit_line(line)?)?;
                }
            }
            other => bail!("unexpected coastline geometry {other:?}"),
        }
    }

    Ok(format!(
        "//! Vendored world coastline geometry for the map view.\n\
         //!\n\
         //! @generated by `cargo xtask gen-map-data` from Natural Earth `ne_110m_coastline`\n\
         //! (public domain), pinned at nvkelso/natural-earth-vector `{NE_REF}`.\n\
         //! Source: https://github.com/nvkelso/natural-earth-vector/blob/{NE_REF}/geojson/ne_110m_coastline.geojson\n\
         //!\n\
         //! Each entry is one coastline polyline as `(longitude, latitude)` degree pairs,\n\
         //! rounded to two decimals. Do not edit by hand -- run `cargo xtask gen-map-data`\n\
         //! to refresh; the data is committed so the build stays offline.\n\
         #![cfg_attr(rustfmt, rustfmt::skip)]\n\
         \n\
         /// World coastlines as `(lon, lat)` polylines in degrees.\n\
         pub static COASTLINE: &[&[(f32, f32)]] = &[\n\
         {body}];\n"
    ))
}

/// Emit one `&[(lon, lat), ...]` polyline literal from a GeoJSON coordinate array.
fn emit_line(coords: &Value) -> Result<String> {
    let pts = coords.as_array().context("line coordinates not an array")?;
    let mut out = String::from("&[");
    for (i, pt) in pts.iter().enumerate() {
        let lon = pt[0].as_f64().context("coordinate longitude")?;
        let lat = pt[1].as_f64().context("coordinate latitude")?;
        if i > 0 {
            out.push_str(", ");
        }
        out.push('(');
        out.push_str(&fmt_coord(lon));
        out.push_str(", ");
        out.push_str(&fmt_coord(lat));
        out.push(')');
    }
    out.push(']');
    Ok(out)
}

fn gen_zone_coords() -> Result<String> {
    let raw = fetch(&format!(
        "https://raw.githubusercontent.com/eggert/tz/{TZ_REF}/zone1970.tab"
    ))?;

    let mut zones: Vec<(String, f64, f64)> = Vec::new();
    for line in raw.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split('\t');
        let _codes = fields.next().context("zone1970 row missing codes")?;
        let coords = fields.next().context("zone1970 row missing coordinates")?;
        let name = fields.next().context("zone1970 row missing name")?;
        let (lat, lon) =
            parse_iso6709(coords).with_context(|| format!("parsing coordinates for {name}"))?;
        zones.push((name.to_string(), lat, lon));
    }
    zones.sort_by(|a, b| a.0.cmp(&b.0));
    zones.dedup_by(|a, b| a.0 == b.0);

    let mut body = String::new();
    for (name, lat, lon) in &zones {
        let (lat_s, lon_s) = (fmt_coord(*lat), fmt_coord(*lon));
        writeln!(body, "    ({name:?}, {lat_s}, {lon_s}),")?;
    }

    Ok(format!(
        "//! Vendored representative coordinates for IANA time zones.\n\
         //!\n\
         //! @generated by `cargo xtask gen-map-data` from the IANA time zone database\n\
         //! `zone1970.tab` (public domain), pinned at eggert/tz `{TZ_REF}`.\n\
         //! Source: https://github.com/eggert/tz/blob/{TZ_REF}/zone1970.tab\n\
         //!\n\
         //! Each entry is `(iana_name, latitude_deg, longitude_deg)`, sorted by name for\n\
         //! binary search. Coordinates are the zone's representative location. Do not edit\n\
         //! by hand -- run `cargo xtask gen-map-data` to refresh; the data is committed so\n\
         //! the build stays offline.\n\
         #![cfg_attr(rustfmt, rustfmt::skip)]\n\
         \n\
         /// Representative `(latitude, longitude)` in degrees for IANA zones, sorted by name.\n\
         pub static ZONE_COORDS: &[(&str, f32, f32)] = &[\n\
         {body}];\n"
    ))
}

/// Parse an ISO 6709 `±DDMM[SS]±DDDMM[SS]` coordinate into decimal degrees.
fn parse_iso6709(s: &str) -> Result<(f64, f64)> {
    let bytes = s.as_bytes();
    let split = (1..bytes.len())
        .find(|&i| bytes[i] == b'+' || bytes[i] == b'-')
        .with_context(|| format!("no longitude sign in {s:?}"))?;
    let lat = parse_component(&s[..split], 2)?;
    let lon = parse_component(&s[split..], 3)?;
    Ok((lat, lon))
}

/// Parse one `±D{deg_digits}MM[SS]` component into signed decimal degrees.
fn parse_component(s: &str, deg_digits: usize) -> Result<f64> {
    let sign = match s.as_bytes().first() {
        Some(b'+') => 1.0,
        Some(b'-') => -1.0,
        _ => bail!("bad sign in {s:?}"),
    };
    let digits = &s[1..];
    if digits.len() < deg_digits {
        bail!("coordinate component {s:?} too short");
    }
    let deg: f64 = digits[..deg_digits]
        .parse()
        .with_context(|| format!("degrees in {s:?}"))?;
    let rest = &digits[deg_digits..];
    let (min, sec): (f64, f64) = match rest.len() {
        0 => (0.0, 0.0),
        2 => (rest.parse()?, 0.0),
        4 => (rest[..2].parse()?, rest[2..].parse()?),
        _ => bail!("odd coordinate component length in {s:?}"),
    };
    Ok(sign * (deg + min / 60.0 + sec / 3600.0))
}
